'use client'

import { useState } from 'react'
import { FileSignature,Plus,Sparkles,Trash2 } from 'lucide-react'
import FormalContract from './FormalContract'

type Doc={id:number;type:string;customer:string;project:string;status:string;content?:string;approvedAt?:string;signature?:string;contractorSignature?:string;customerSignature?:string;contractDate?:string}
type Data={docs:Doc[];settings:{businessName:string;phone:string;email:string;address:string;estimateTerms:string};[key:string]:any}

export default function ContractWorkspace({data,setData,ai}:{data:Data,setData:(d:any)=>void,ai:(mode:string,input:string)=>Promise<string>}){
 const [customer,setCustomer]=useState(''),[project,setProject]=useState(''),[details,setDetails]=useState(''),[generated,setGenerated]=useState(''),[working,setWorking]=useState(false),[error,setError]=useState('')
 async function generate(){if(!customer.trim()||!project.trim()||!details.trim())return;setWorking(true);setError('');try{const text=await ai('contract',`Create a professional construction contract draft. Contractor: ${data.settings.businessName||'Contractor'}. Customer: ${customer}. Project: ${project}. Project details/scope: ${details}. Terms: ${data.settings.estimateTerms}. Include scope of work, contract price/payment terms if supplied, schedule language, change-order requirement, responsibilities, warranties/limitations as appropriate, cancellation/termination language, dispute/general terms, and signature section. Do not invent licenses, insurance, prices, dates, warranties, or legal facts that were not supplied.`);setGenerated(text)}catch(e:any){setError(e?.message||'Contract could not be generated.')}finally{setWorking(false)}}
 function save(){if(!generated.trim())return;setData({...data,docs:[{id:Date.now(),type:'Contracts',customer:customer.trim(),project:project.trim(),status:'Awaiting Signatures',content:generated},...data.docs]});setGenerated('');setCustomer('');setProject('');setDetails('')}
 const docs=data.docs.filter(d=>d.type==='Contracts')
 return <div className="workspace"><div className="workspaceHead"><div><h2><FileSignature size={20}/> Contracts</h2><p>Create the agreement, collect contractor and customer signatures, then produce a formal signed contract.</p></div></div><div className="builderGrid inlineAction"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Project<input value={project} onChange={e=>setProject(e.target.value)}/></label><label className="full">Scope, price, schedule and contract details<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Describe the agreed work, price/payment schedule, expected timing and any special terms..."/></label><button className="primary full" disabled={!customer.trim()||!project.trim()||!details.trim()||working} onClick={generate}><Sparkles size={16}/>{working?'Creating Contract…':'Create Contract with AI'}</button>{error&&<div className="generated full"><small>CONTRACT NOT GENERATED</small><pre>{error}</pre></div>}{generated&&<div className="generated full"><small>DRAFT — REVIEW BEFORE SIGNING</small><pre>{generated}</pre><button className="primary" onClick={save}><Plus size={16}/> Save & Send to Signatures</button></div>}</div>{docs.length?docs.map(d=><div key={d.id}><FormalContract doc={d} data={data} setData={setData}/><button className="ghost noPrint" onClick={()=>setData({...data,docs:data.docs.filter(x=>x.id!==d.id)})}><Trash2 size={15}/> Delete Contract</button></div>):<div className="empty"><FileSignature/><b>No contracts yet.</b></div>}</div>
}
