'use client'
import {useMemo,useState} from 'react'
import {Camera,Image as ImageIcon,Plus,Printer,Trash2,Sparkles,Upload} from 'lucide-react'
type Data={files:any[];projects?:any[];[key:string]:any}
export default function ProjectGallery({data,setData}:{data:Data,setData:(d:any)=>void}){
 const[name,setName]=useState(''),[project,setProject]=useState(''),[category,setCategory]=useState('Remodel'),[before,setBefore]=useState<File|null>(null),[after,setAfter]=useState<File|null>(null),[description,setDescription]=useState(''),[filter,setFilter]=useState('All'),[working,setWorking]=useState(false),[insight,setInsight]=useState('')
 const items=(data.files||[]).filter((f:any)=>f.category==='Project Gallery');const categories=['All',...Array.from(new Set(items.map((i:any)=>i.galleryCategory||'Other')))];const shown=useMemo(()=>filter==='All'?items:items.filter((i:any)=>(i.galleryCategory||'Other')===filter),[items,filter])
 async function upload(file:File,label:string){const fd=new FormData();fd.append('file',file);const p=(data.projects||[]).find((x:any)=>x.name===project);fd.append('customer',p?.customer||'Unassigned');fd.append('project',project||'Unassigned');fd.append('category','Photos');const r=await fetch('/api/files',{method:'POST',body:fd});const b=await r.json();if(!r.ok)throw Error(b.error||'Upload failed');return{id:b.file.id,name:b.file.filename,label}}
 async function analyze(){setWorking(true);setInsight('');try{const context=`Project: ${project||'Unassigned'}\nCategory: ${category}\nDescription: ${description||'Not provided'}\nPhoto files: ${[before?.name,after?.name].filter(Boolean).join(', ')||'none'}`;const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'general',input:`Act as a construction photo organizer. Based only on this metadata, suggest: likely photo category, useful tags, visible-work checklist the contractor should verify, and anything that cannot be determined from the metadata. Never claim you visually inspected an image.\n${context}`})});const b=await r.json();if(!r.ok)throw Error();setInsight(String(b.text||''))}catch{setInsight('Photo intelligence could not run. You can still securely file the photos.')}finally{setWorking(false)}}
 async function add(){if(!name.trim()||!before||!after)return;setWorking(true);try{const b=await upload(before,'Before'),a=await upload(after,'After');setData({...data,files:[{id:Date.now(),name:name.trim(),project,category:'Project Gallery',galleryCategory:category,beforeFileId:b.id,afterFileId:a.id,beforeFilename:b.name,afterFilename:a.name,notes:description.trim(),photoInsight:insight,featured:true,createdAt:new Date().toISOString()},...(data.files||[])]});setName('');setBefore(null);setAfter(null);setDescription('');setInsight('')}finally{setWorking(false)}}
 async function openFile(id:string){const r=await fetch('/api/files/'+id);const b=await r.json();if(r.ok&&b.url)window.open(b.url,'_blank','noopener,noreferrer')}
 return <div className="workspace"><div className="workspaceHead"><div><h2><Camera/> Photo Intelligence & Before/After</h2><p>Securely file jobsite photos by project, organize them, and generate cautious AI filing suggestions.</p></div></div><div className="builderGrid noPrint"><label>Gallery title<input value={name} onChange={e=>setName(e.target.value)} placeholder="Kitchen transformation"/></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Unassigned</option>{(data.projects||[]).map((p:any)=><option key={p.id}>{p.name}</option>)}</select></label><label>Project type<select value={category} onChange={e=>setCategory(e.target.value)}>{['Remodel','Kitchen','Bathroom','Deck','Roofing','Garage','Pole Barn','New Construction','Flooring','Exterior','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Before photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setBefore(e.target.files?.[0]||null)}/></label><label>After photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setAfter(e.target.files?.[0]||null)}/></label><label className="full">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Work completed, materials, room/area, field notes…"/></label><button className="ghost" disabled={working} onClick={analyze}><Sparkles/> {working?'Analyzing…':'Photo Intelligence'}</button><button className="primary" disabled={working||!name.trim()||!before||!after} onClick={add}><Upload/> Securely File Photos</button>{insight&&<div className="full dashPanel"><b>AI filing suggestions</b><p style={{whiteSpace:'pre-wrap'}}>{insight}</p><small>Suggestions are based on supplied metadata and must be field-verified.</small></div>}</div><div className="galleryToolbar noPrint"><div>{categories.map((x:any)=><button key={x} className={filter===x?'primary':'ghost'} onClick={()=>setFilter(x)}>{x}</button>)}</div><button className="ghost" onClick={()=>window.print()}><Printer size={15}/> Print Portfolio</button></div>{shown.length?<div className="portfolioGrid">{shown.map((i:any)=><article className="portfolioCard" key={i.id}><div className="portfolioInfo"><small>{i.galleryCategory||'Other'}</small><h3>{i.name}</h3>{i.project&&<b>{i.project}</b>}<p>{i.notes}</p><div><button className="ghost noPrint" onClick={()=>openFile(i.beforeFileId)}>Before · {i.beforeFilename}</button><button className="ghost noPrint" onClick={()=>openFile(i.afterFileId)}>After · {i.afterFilename}</button></div>{i.photoInsight&&<small>{i.photoInsight}</small>}<button className="ghost noPrint" onClick={()=>setData({...data,files:data.files.filter((f:any)=>f.id!==i.id)})}><Trash2 size={14}/> Remove record</button></div></article>)}</div>:<div className="empty"><ImageIcon/><b>No before-and-after projects yet.</b><span>Add photos to the secure project file cabinet.</span></div>}</div>
}
