'use client'

import { useEffect,useState } from 'react'
import { ArrowLeft,HardHat,Play } from 'lucide-react'
import JobTracker from '../components/JobTracker'
type Project={id:number;customer:string;name:string;status:string;date:string;amount:number}
export default function JobsPage(){
 const[data,setData]=useState<any>(null),[company,setCompany]=useState('Construction Company'),[selected,setSelected]=useState<Project|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[onboarding,setOnboarding]=useState(false),[role,setRole]=useState('owner')
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.status===401){location.href='/login';return}if(!r.ok)throw new Error('Workspace could not be loaded');const w=await r.json();const d={...w.data,projects:Array.isArray(w.data?.projects)?w.data.projects:[],receipts:Array.isArray(w.data?.receipts)?w.data.receipts:[],payroll:Array.isArray(w.data?.payroll)?w.data.payroll:[],docs:Array.isArray(w.data?.docs)?w.data.docs:[],timeEntries:Array.isArray(w.data?.timeEntries)?w.data.timeEntries:[],settings:w.data?.settings||{}};setCompany(w.companyName||'Construction Company');setRole(w.role||'owner');setData(d);const q=new URLSearchParams(location.search);const id=Number(q.get('project'));if(id){const p=d.projects.find((x:Project)=>x.id===id);if(p){setSelected(p);setOnboarding(q.get('onboarding')==='1')}}}catch(e:any){setError(e.message)}})()},[])
 useEffect(()=>{if(!data||!['owner','manager'].includes(role))return;setSaving(true);const t=setTimeout(async()=>{try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)setError('Job changes could not be saved.')}catch{setError('Job changes could not be saved.')}finally{setSaving(false)}},450);return()=>clearTimeout(t)},[data,role])
 if(error)return <main style={{padding:30}}><b>{error}</b></main>;if(!data)return <main style={{padding:30,display:'flex',gap:10,alignItems:'center'}}><HardHat/> Loading job workspace…</main>
 if(selected){const current=data.projects.find((p:Project)=>p.id===selected.id)||selected;return <main style={{maxWidth:1200,margin:'0 auto',padding:20}}><JobTracker project={current} data={data} setData={setData} onClose={()=>{setSelected(null);setOnboarding(false);history.replaceState({},'', '/jobs')}} onboarding={onboarding}/></main>}
 return <main style={{maxWidth:1100,margin:'0 auto',padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:24}}><div><a href="/"><ArrowLeft size={16}/> Dashboard</a><h1>Start & Track Jobs</h1><p>{company} · expenses, labor hours, and customer-ready job reports</p></div><small>{role==='employee'?'Employee view':saving?'Saving…':'Saved'}</small></div><div style={{display:'grid',gap:12}}>{data.projects.length?data.projects.map((p:Project)=><div key={p.id} style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:18,display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><div style={{flex:1,minWidth:220}}><strong style={{fontSize:18}}>{p.name}</strong><div style={{color:'#667085'}}>{p.customer} · {p.status} · Estimate ${Number(p.amount||0).toLocaleString()}</div></div><button onClick={()=>setSelected(p)} style={{border:0,borderRadius:10,padding:'11px 15px',fontWeight:800,background:p.status==='In Progress'?'#111827':'#f4a622',color:p.status==='In Progress'?'#fff':'#111827',display:'flex',gap:7}}><Play size={16}/>{p.status==='In Progress'?'Track Job':'Start Job'}</button></div>):<div style={{padding:30}}>Create a project first, then return here to start and track it.</div>}</div></main>}
